### ISSUE TITLE
Mixins should apply vars and functions in the scope of the mixin definition

### ISSUE THREAD

**Issue by ebryn** [prototypal-io/prius#13]
https://github.com/prototypal-io/prius/pull/11

We're currently applying mixins in the scope of the `@apply`, which is what we thought would be the behavior, but after talking to @tabatkins we realized that they should be using the scope at the time of definition.

**Comment by tabatkins** [comment]
Note: this is a direct consequence of using custom properties for the mixin definition; they get var() refs substituted in at computed-value time (before they inherit).  If some new syntax was used instead, the behavior could be different.

**Comment by mmun** [comment]
My latest idea for configurable mixins is passing a block to `@apply` that defines local vars.

```css
.bar {
  @apply(--crazy-margin) {
    size: 5px;
  }
}

:root {
  --crazy-margin: {
    margin: local(size) calc(2 * local(size)) calc(3 * local(size)) calc(4 * local(size));
  }
}
```

But honestly I am not too sure about using `@apply` + custom properties for mixins, rather than just defining custom at-rules directly, e.g. `@crazy-margin(5px)` above.
